# Generated by Django 3.1.7 on 2021-03-14 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_jobopening'),
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('investor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='investors.investor')),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='startups.startup')),
            ],
        ),
    ]
