# Generated by Django 3.1.7 on 2021-03-27 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0012_auto_20210326_1457'),
        ('investors', '0002_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='investment',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.investor'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startups.startup'),
        ),
    ]
