# Generated by Django 3.1.7 on 2021-03-09 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Startup',
        ),
    ]
