# Generated by Django 3.1.7 on 2021-03-10 15:57

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20210310_1657'),
        ('startups', '0002_delete_startup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user_type')),
                ('company_name', models.CharField(max_length=300)),
                ('snapshot', models.TextField()),
                ('company_size', models.IntegerField(default=1)),
                ('location', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('registered', models.BooleanField()),
                ('logo', models.ImageField(upload_to='media/startups/logos')),
                ('team', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, size=None)),
                ('work_benefits', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=400), blank=True, size=None)),
                ('category', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
            ],
        ),
    ]
