# Generated by Django 3.1.7 on 2021-03-14 12:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_startup'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.TextField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('application_link', models.CharField(max_length=600)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('requirements', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('extra_info', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='startups.startup')),
            ],
        ),
    ]
