# Generated by Django 3.1.7 on 2021-03-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_jobopening'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='business_model',
            field=models.CharField(choices=[('B2C', 'B2C'), ('B2B', 'B2B'), ('C2B', 'B2B'), ('C2C', 'C2C')], default='B2C', max_length=200),
        ),
    ]
