# Generated by Django 3.1.7 on 2021-03-19 18:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0005_startup_business_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='gallery',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='media/startups/<django.db.models.fields.CharField>/gallery'), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='startup',
            name='pitch',
            field=models.FileField(null=True, upload_to='media/startups/<django.db.models.fields.CharField>/pitch'),
        ),
    ]
