# Generated by Django 3.1.7 on 2021-03-19 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0006_auto_20210319_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='gallery',
        ),
        migrations.AddField(
            model_name='jobopening',
            name='job_type',
            field=models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='mode',
            field=models.CharField(choices=[('Remote', 'Remote'), ('In Person', 'In Person')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='StartupGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/startups/<django.db.models.fields.related.OneToOneField>/gallery')),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='startups.startup')),
            ],
        ),
    ]
