# Generated by Django 3.1.7 on 2021-03-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0008_auto_20210319_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='logo',
            field=models.ImageField(upload_to='media/startups/<django.db.models.fields.CharField>/logo'),
        ),
    ]
