# Generated by Django 3.1.7 on 2021-03-26 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0010_auto_20210326_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startupgallery',
            options={'verbose_name_plural': "Startups' Gallery"},
        ),
    ]
