# Generated by Django 3.1.7 on 2021-03-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0012_auto_20210326_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
