# Generated by Django 3.1.7 on 2021-03-09 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_type',
            old_name='is_student',
            new_name='is_investor',
        ),
        migrations.RenameField(
            model_name='user_type',
            old_name='is_teach',
            new_name='is_startup',
        ),
    ]
